### ISSUE TITLE
Porque não passar os parametros em um dicionário

### ISSUE THREAD

**Issue by danielortiz** [Deividy/frete#1]
Olá, estou desenvolvendo um package para reaction commerce (em meteor) e seu modulo esta sendo muito util =)

Uma dúvida, porque não ao invés de passar os parametros desta forma atual

```
frete()
    .cepOrigem('13467460')
    .peso(1)
    .formato(1)
    .comprimento(16)
    .altura(2)
    .largura(11)
    .diametro(1)
    .maoPropria('N')
    .valorDeclarado(50)
    .avisoRecebimento('S')
    .servico(frete.codigos.sedex)
    .preco('13466321', function (err, results) {
        console.log(err);
        console.log(results);
    });
```

não passar na forma de um objeto

```
frete({
    cepOrigem: '13467460',
    peso: 1,
    formato: 1
}).preco(function(er, res){

})
```

Digo isso porque tive alguns problemas para integrar esta função com alguns métodos, como o Meteor.wrapAsync. Além disso acho que ficaria mais legível e intuitivo. 

Parabens pelo módulo =)

**Comment by Deividy** [comment]
Valeu, que bom que vc curtiu! :)

Bom, a principio ele aceita um objeto, só que nesse caso tem que ser o objeto direto da API, sem o cool camel case (e.g. `frete({ sCepOrigem: 'xxx' })`). 
Mas a sua ideia é boa, e seria uma boa aceitar os args assim tb, e bem trivial para implementar.

Deixa eu preparar um commit aqui...

**Comment by Deividy** [comment]
Ta la: https://github.com/Deividy/frete#objeto-as-config--more-usages

Só mandar um update :)
