### ISSUE TITLE
Cubagem

### ISSUE THREAD

**Issue by meciasbueno** [Deividy/frete#15]
Faz o cálculo de cubagem também?
Tipo, como eu faria para chamar esses métodos para um carrinho de compras com vários itens de diferentes tamanhos e peso?

**Comment by EduardoJM** [comment]
Não faz. A lib é "apenas" uma implementação/integração com o webservice SOAP dos correios.

Quando o carrinho tem vários itens, você precisa implementar algum algoritmo pra agrupar esses itens dentro dos tamanhos de caixa que você tem e calcular o frete pra essas caixas.

**Comment by augustosnk12** [comment]
Boa tarde!

Alguém aqui encontrou alguma lógica para lidar com o cálculo de frete com vários itens?

**Comment by Deividy** [comment]
O correios fornece essa tabela com os limites de dimensões dos pacotes:
https://www2.correios.com.br/sistemas/precosprazos/Formato.cfm

E aqui tem uma thread com alguns comentários uteis para isso:
https://pt.stackoverflow.com/questions/246817/calcular-frete-dos-correios-para-diversos-produtos

🤗
