### ISSUE TITLE
Como armazenar o responseJSON? 

### ISSUE THREAD

**Issue by michelmfreitas** [Deividy/frete#2]
Fiquei na dúvida como pegar o retorno do responseJSON do resultado. É assíncrono?

frete() retorna uma promise?

**Comment by Deividy** [comment]
[rtfm](https://github.com/Deividy/frete#calculo-simples-de-prazo)

Mas, podemos fazer retornar uma promise sim, seria bem trivial, só mudar algumas coisas [aqui](https://github.com/Deividy/frete/blob/master/frete.js#L263)

**Comment by Deividy** [comment]
Agora temos support para promises! 🥇
