### ISSUE TITLE
Resource request: Typescript typing

### ISSUE THREAD

**Issue by kayotimoteo** [Deividy/frete#4]
It would be a very interesting feature, in the future I can make a pull request. :D

**Comment by Deividy** [comment]
well, our little frete is very simple and we directly manipulate the object prototype (which makes TypeScript mad), so, I'm not sure if we can implement this ' typing stuff' without harm our design.

but yeah, if you can do this PR I'm sure it will be appreciated for all. also thanks for the suggestion!
