### ISSUE TITLE
Declaração de tipos do Typescript não está funcionando

### ISSUE THREAD

**Issue by vitorgouveia** [Deividy/frete#7]
Estou começando a usar essa package no meu projeto mas percebi que os tipos não estão pegando, ele não me fala quais parâmetros passar e etc.

**Comment by vitorgouveia** [comment]
por enquanto resolvi criando um arquivo de declaração no meu projeto com o mesmo conteúdo do arquivo que está no repositório

**Comment by EduardoJM** [comment]
O arquivo foi adicionado ao repositório, mas acredito que não tenha sido publicado como nova versão ao **npm**, visto que a última atualização do **npm** foi há 9 meses... É preciso que o @Deividy atualize lá :)

**Comment by Deividy** [comment]
oops... tinha faltado o `npm publish`; publicado. :)
